const state={page:"tickets",role:"user",photos:[],tickets:[{id:"#1024",title:"Drucker im Besprechungsraum defekt",priority:"Hoch",status:"Offen",date:"Heute, 09:14",photos:2},{id:"#1023",title:"VPN-Zugang funktioniert nicht",priority:"Mittel",status:"In Bearbeitung",date:"Gestern, 16:32",photos:0},{id:"#1022",title:"Beschädigtes Notebook dokumentieren",priority:"Kritisch",status:"Wartend",date:"Gestern, 11:08",photos:4}]};
const app=document.getElementById("app"),pageTitle=document.getElementById("pageTitle");
function tickets(){let html="";state.tickets.forEach(t=>{html+='<article class="card ticket"><div style="flex:1"><div class="row"><span class="title">'+t.title+'</span><span class="status">'+t.status+'</span></div><div class="muted">'+t.id+" · "+t.date+" · Priorität: "+t.priority+"</div>"+(t.photos?'<div class="muted">📷 '+t.photos+" Fotos dokumentiert</div>":"")+"</div></article>";});return html+'<div class="card"><b>Mobile PoC</b><p class="muted">Ticket-Erfassung, Kamera/Galerie und Admin-Übersicht sind prototypisch abgebildet.</p></div>';}
function form(){return '<section class="card form"><label>Titel<input id="ticketTitle" placeholder="z. B. Drucker defekt"></label><label>Beschreibung<textarea id="ticketDescription" placeholder="Was ist passiert?"></textarea></label><label>Priorität<select id="priority"><option>Niedrig</option><option selected>Mittel</option><option>Hoch</option><option>Kritisch</option></select></label><div class="camera"><div style="font-size:30px">📷</div><b>Fotos dokumentieren</b><p class="muted">Kamera öffnen oder Bilder aus der Galerie auswählen.</p><input id="photoInput" type="file" accept="image/*" capture="environment" multiple></div><div id="preview" class="preview"></div><button id="create" class="primary">Ticket erstellen</button></section>';}
function admin(){let html='<div class="kpis"><div class="card kpi"><span class="muted">Offen</span><strong>2</strong></div><div class="card kpi"><span class="muted">Heute</span><strong>8</strong></div><div class="card kpi"><span class="muted">Kritisch</span><strong>1</strong></div><div class="card kpi"><span class="muted">Fotos</span><strong>6</strong></div></div><section class="card"><div class="row"><b>Tickets nach Status</b><span class="muted">PoC</span></div><p class="muted">Offen</p><div class="bar"><i style="width:55%"></i></div><p class="muted">In Bearbeitung</p><div class="bar"><i style="width:32%"></i></div><p class="muted">Wartend</p><div class="bar"><i style="width:18%"></i></div></section><section class="card"><b>Letzte Tickets</b>';state.tickets.forEach(t=>{html+='<p><span class="title">'+t.id+"</span> · "+t.title+'<br><span class="muted">'+t.priority+" · "+t.status+" · 📷 "+t.photos+"</span></p>";});return html+"</section>";}
function render(){pageTitle.textContent=state.page==="tickets"?"Meine Tickets":state.page==="new"?"Neues Ticket":"Admin Dashboard";app.innerHTML=state.page==="tickets"?tickets():state.page==="new"?form():admin();}
document.querySelectorAll(".tabs button").forEach(btn=>btn.addEventListener("click",()=>{state.page=btn.dataset.page;render();document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===btn));}));
document.getElementById("roleBtn").addEventListener("click",()=>{state.role=state.role==="user"?"admin":"user";document.getElementById("roleBtn").textContent=state.role==="admin"?"User":"Admin";state.page=state.role==="admin"?"admin":"tickets";render();});
document.addEventListener("change",e=>{if(e.target.id==="photoInput"){state.photos=Array.from(e.target.files);document.getElementById("preview").innerHTML=state.photos.map(f=>'<img src="'+URL.createObjectURL(f)+'" alt="Foto">').join("");}});
document.addEventListener("click",e=>{if(e.target.id==="create"){const t=document.getElementById("ticketTitle").value.trim()||"Neues Ticket";state.tickets.unshift({id:"#"+(1025+state.tickets.length),title:t,priority:document.getElementById("priority").value,status:"Offen",date:"Gerade eben",photos:state.photos.length});state.photos=[];state.page="tickets";render();}});render();